operator:
  image: sumon124816/kubeslice
  pullPolicy: Always
  logLevel: INFO
  tag: worker-7

## Base64 encoded secret values from controller cluster
controllerSecret:
  namespace:
  endpoint:
  ca.crt:
  token:

cluster:
  name:
  nodeIp: # This field is deprecated. You can set nodeIPs through cluster spec.
  endpoint:

router:
  image: docker.io/aveshasystems/cmd-nse-vl3
  tag: 1.0.6
  pullPolicy: IfNotPresent                                                                                     

routerSidecar:
  image: docker.io/aveshasystems/kubeslice-router-sidecar
  tag: 1.4.6
  pullPolicy: IfNotPresent


gateway:
  image: sumon124816/kubeslice
  tag: gw-sidecar-1
  pullPolicy: IfNotPresent
  logLevel: INFO

gatewayEdge:
  image: aveshasystems/slicegw-edge
  tag: 1.0.6

openvpn:
  server:
    image: docker.io/aveshasystems/openvpn-server.alpine
    tag: 1.0.4
    pullPolicy: IfNotPresent
  client:
    image: docker.io/aveshasystems/openvpn-client.alpine
    tag: 1.0.4
    pullPolicy: IfNotPresent

wireguard:
  server:
    image: sumon124816/wireguard
    tag: server-7
    pullPolicy: IfNotPresent
  client:
    image: sumon124816/wireguard
    tag: client-7
    pullPolicy: IfNotPresent

dns:
  image: docker.io/aveshasystems/dns
  tag: 0.1.4
  pullPolicy: IfNotPresent

workerInstaller:
  image: docker.io/aveshasystems/worker-installer
  tag: 1.5.0

jaeger:
  enabled: false

events:
  disabled: true

imagePullSecrets:
  - name: regcred

# change ths value for intracluster where controller cluster is in same cluster as worker as is different from default
controllerNamespace: kubeslice-controller

global:
  imageRegistry: docker.io/aveshasystems
  profile:
    openshift: false

# enable/disable network component installation
kubesliceNetworking:
  enabled: true

nsm:
  spire:
    priorityClassName: ""
    spire-server:
      priorityClassName: ""
    spiffe-csi-driver:
      priorityClassName: ""
