# Default values for k-native.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubeslice:
  rbacproxy:
    image: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
  controller:
    logLevel: debug
    rbacResourcePrefix: kubeslice-rbac
    projectnsPrefix: kubeslice
    endpoint:
    image: sumon124816/kubeslice
    tag: controller-1
    pullPolicy: IfNotPresent
  ovpnJob:
    image: sumon124816/kubeslice
    tag: cert-gen-final
  events:
    disabled: false
