# Default values for k-native.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubeslice:
  rbacproxy:
    image: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
  controller:
    logLevel: debug
    rbacResourcePrefix: kubeslice-rbac
    projectnsPrefix: kubeslice
    endpoint:
    image: sumon124816/kubeslice
    tag: controller-oc
    pullPolicy: Always
  ovpnJob:
    image: ghcr.io/kube-slice/gateway-certs-generator
    tag: v0.7.0-ac
  events:
    disabled: false

ocm:
  enabled: false
  placement:
    create: true
    name: global

distro:
  openshift: false
