# Default values for k-native.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubeslice:
  rbacproxy:
    image: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
  controller:
    logLevel: debug
    rbacResourcePrefix: kubeslice-rbac
    projectnsPrefix: kubeslice
    endpoint:
    image: ghcr.io/kube-slice/kubeslice-controller
    tag: v1.9.0-ac
    pullPolicy: IfNotPresent
  ovpnJob:
    image: ghcr.io/kube-slice/gateway-certs-generator
    tag: v0.7.0-ac
  events:
    disabled: false
