---
# Default values for nsm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
  
insecure: true
global:
  nsm_docker_existingImagePullSecret: "kubeslice-image-pull-secret"
  # IF You dont have existing secret then pass all below values it will create new secret "avesha-docker-ips"
  ## MANDOTORY FIELDS IF EXISTING SECRET NOT PRESENT ##
  nsm_docker_imagePullSecrets:
    repository:
    username: ''
    password: ''
    email: ''
  imageRegistry: ghcr.io/kube-slice
  # set to true to enable Jaeger tracing for NSM components
  JaegerTracing: true

forwardingPlane:
  kernelImageRegistry: sumon124816/kubeslice
  kernelImageTag: kernel-spire

nsmgr:
  imageRegistry: sumon124816/kubeslice
  imageTag: nsm-spire
  waitForItImageRegistry: wait-for-it
  waitForItImageTag: v1.1.0-ac
  excludePrefixesImageRegistry: cmd-exclude-prefixes-k8s
  excludePrefixesImageTag: v1.5.4

registryK8sImageRegistry: sumon124816/kubeslice
registryK8sImageTag: registry-spire

nscgrpc:
  cmdnscgrpcServerImageRegistry: sumon124816/kubeslice
  cmdnscgrpcServerImageTag: nsc-sidecar