{{- if and .Values.ocm.enabled .Values.ocm.placement.create }}

apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.ocm.placement.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterSets:
    - global
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
      tolerationSeconds: 604800
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
      tolerationSeconds: 604800
{{- end }}
